#!/usr/bin/env python3
import argparse
from pathlib import Path

from topology import topology


def fmt(cpus):
    return ",".join(str(c) for c in cpus)


def split_primary_smt_groups(topo, socket_id):
    groups = [
        g["cpus"]
        for g in topo["smt_groups"]
        if str(g["socket"]) == str(socket_id) and len(g["cpus"]) >= 2
    ]
    groups.sort(key=lambda xs: min(xs))
    primary = [xs[0] for xs in groups]
    siblings = [xs[1] for xs in groups]
    return primary, siblings


def choose_socket(topo, preferred):
    sockets = sorted(topo["sockets"].keys(), key=lambda x: int(x) if str(x).isdigit() else str(x))
    if preferred is not None and str(preferred) in topo["sockets"]:
        return str(preferred)
    if not sockets:
        raise SystemExit("No CPU sockets found from lscpu output")
    return str(sockets[0])


def choose_node_for_socket(topo, socket_id):
    socket_cpus = set(topo["sockets"].get(str(socket_id), []))
    best_node = None
    best_count = -1
    for node, cpus in topo["nodes"].items():
        count = len(socket_cpus.intersection(cpus))
        if count > best_count:
            best_node = node
            best_count = count
    return str(best_node if best_node is not None else 0)


def take(values, count, offset=0):
    selected = values[offset : offset + count]
    if len(selected) < count:
        raise SystemExit(f"Need {count} CPUs from {values}, got {len(selected)}")
    return selected


def choose_paired_cpus(topo, socket_id, count, offset_groups=0):
    primary, siblings = split_primary_smt_groups(topo, socket_id)
    if primary and siblings and count >= 2:
        groups_needed = (count + 1) // 2
        left = take(primary, groups_needed, offset=offset_groups)
        right = take(siblings, groups_needed, offset=offset_groups)
        return (left + right)[:count]
    cpus = sorted(topo["sockets"].get(str(socket_id), []))
    return take(cpus, count, offset=offset_groups)


def render_env(args):
    topo = topology()
    server_socket = choose_socket(topo, args.server_socket)
    loadgen_socket = args.loadgen_socket
    if loadgen_socket is None:
        sockets = sorted(topo["sockets"].keys(), key=lambda x: int(x) if str(x).isdigit() else str(x))
        loadgen_socket = sockets[1] if len(sockets) > 1 else sockets[0]

    primary, siblings = split_primary_smt_groups(topo, server_socket)
    if not primary:
        cpus = sorted(topo["sockets"].get(server_socket, []))
        half = max(1, len(cpus) // 2)
        primary = cpus[:half]
        siblings = cpus[half:]

    server = take(primary, args.server_cores)
    loadgen = choose_paired_cpus(topo, loadgen_socket, args.loadgen_cores)

    if args.offline_policy == "same_smt":
        offline = take(siblings, args.offline_cores)
        offline_mems = choose_node_for_socket(topo, server_socket)
    elif args.offline_policy == "same_socket":
        offline = take(primary, args.offline_cores, offset=args.server_cores)
        offline_mems = choose_node_for_socket(topo, server_socket)
    elif args.offline_policy == "cross_numa":
        other_sockets = [
            s
            for s in sorted(topo["sockets"].keys(), key=lambda x: int(x) if str(x).isdigit() else str(x))
            if str(s) != str(server_socket)
        ]
        if not other_sockets:
            raise SystemExit("cross_numa requested but only one socket was detected")
        offline_socket = str(other_sockets[0])
        other_primary, _ = split_primary_smt_groups(topo, offline_socket)
        if not other_primary:
            other_primary = sorted(topo["sockets"].get(offline_socket, []))
        loadgen_groups = max(1, (args.loadgen_cores + 1) // 2)
        offline = take(other_primary, args.offline_cores, offset=loadgen_groups)
        offline_mems = choose_node_for_socket(topo, offline_socket)
    else:
        raise SystemExit(f"Unknown offline policy: {args.offline_policy}")

    overlap = set(server) & set(loadgen) or set(server) & set(offline) or set(loadgen) & set(offline)
    if overlap:
        raise SystemExit(f"Generated overlapping CPU binding: {sorted(overlap)}")

    server_mems = choose_node_for_socket(topo, server_socket)
    loadgen_mems = choose_node_for_socket(topo, loadgen_socket)

    lines = [
        "# Generated by application/generate_env_from_topology.py",
        "# Review these bindings before long experiments.",
        f'export CLAB_IMAGE="{args.image}"',
        f'export DCPERF_MOUNT="{args.dcperf_mount}"',
        f'export RESULTS_ROOT="{args.results_root}"',
        f'export DCPERF_DIR="{args.dcperf_dir}"',
        f'export IBENCH_DIR="{args.ibench_dir}"',
        f'export SPEC_DIR="{args.spec_dir}"',
        "",
        f'export SERVER_CPUSET="{fmt(server)}"',
        f'export SERVER_MEMS="{server_mems}"',
        f'export LOADGEN_CPUSET="{fmt(loadgen)}"',
        f'export LOADGEN_MEMS="{loadgen_mems}"',
        f'export OFFLINE_CPUSET="{fmt(offline)}"',
        f'export OFFLINE_MEMS="{offline_mems}"',
        "",
        'export TAO_MEMSIZE="${TAO_MEMSIZE:-16}"',
        'export TAO_SERVER_PORT="${TAO_SERVER_PORT:-11211}"',
        f'export TAO_INTERFACE_NAME="{args.interface}"',
        'export ULIMIT_NOFILE="${ULIMIT_NOFILE:-65535}"',
        'export TAO_SERVER_PID_PATTERN="${TAO_SERVER_PID_PATTERN:-tao_bench_server}"',
        "",
        'export SERVER_CONTAINER="${SERVER_CONTAINER:-clab-server}"',
        'export LOADGEN_CONTAINER="${LOADGEN_CONTAINER:-clab-loadgen}"',
        'export OFFLINE_CONTAINER="${OFFLINE_CONTAINER:-clab-offline}"',
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Generate a portable env.sh from local CPU topology.")
    ap.add_argument("--server-socket", type=int)
    ap.add_argument("--loadgen-socket", type=int)
    ap.add_argument("--server-cores", type=int, default=8)
    ap.add_argument("--loadgen-cores", type=int, default=16)
    ap.add_argument("--offline-cores", type=int, default=8)
    ap.add_argument("--offline-policy", choices=["same_smt", "same_socket", "cross_numa"], default="same_smt")
    ap.add_argument("--image", default="dcperf-taobench:ready")
    ap.add_argument("--dcperf-mount", default="0")
    ap.add_argument("--results-root", default="/home/lilinzhen/colocate_lab/results/cbs")
    ap.add_argument("--dcperf-dir", default="/home/lilinzhen/colocate_lab/DCPerf")
    ap.add_argument("--ibench-dir", default="/home/lilinzhen/iBench")
    ap.add_argument("--spec-dir", default="/home/lilinzhen/cpu2017")
    ap.add_argument("--interface", default="eno1")
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    text = render_env(args)
    if args.out:
        Path(args.out).write_text(text + "\n")
    else:
        print(text)


if __name__ == "__main__":
    main()
